version: "3.8"

services:
  mongo:
    container_name: mongobd
    build: ./src/server/dbmongo/
    ports:
      - 20017:27017
  mysql: 
    container_name: mysql
    build: ./src/server/dbmysql/
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3306:3306
  ms_orders:
    container_name: orders
    build: ./src/server/ms_1_orders
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 3000:3001
    volumes:
      - ./src/server/ms_1_orders:.
  ms_menus:
    container_name: menus
    build: ./src/server/ms_2_menus
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 3000:3002
    volumes:
      - ./src/server/ms_2_menus:.
  ms_cook:
    container_name: cook
    build: ./src/server/ms_3_cook
    depends_on:
      - mysql
      - mongo
    links:
      - mysql
      - mongo
    ports:
      - 3000:3003
    volumes:
      - ./src/server/ms_3_cook/src:.
  ms_update_food_storage:
    container_name: food_storage
    build: ./src/server/ms_4_update_food_storage
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 3000:3004
    volumes:
      - ./src/server/ms_4_update_food_storage:.

