version: "3.8"

services:
  mongo:
    container_name: mongobd
    build: ./src/server/dbmongo/
    ports:
      - 27017:27017
  mysql: 
    container_name: mysql
    build: ./src/server/dbmysql/
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3306:3306
  ms_menus:
    container_name: menus
    build: ./src/server/ms_1_menus
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 3001:3001
  ms_orders:
    container_name: orders
    build: ./src/server/ms_2_orders
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 3002:3002
  ms_update_food_storage:
    container_name: food_storage
    build: ./src/server/ms_3_food_storage
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 3003:3003
  ms_cook:
      container_name: cook
      build: ./src/server/ms_4_cook
      depends_on:
      - ms_menus
      - ms_orders
      - ms_update_food_storage
      links:
      - ms_menus
      - ms_orders
      - ms_update_food_storage
      ports:
        - 3004:3004
  client:
      container_name: client
      build: ./src/client
      ports:
        - 3000:3000
      env_file:
        - ./.env
      environment:
        - HOST=$HOST
  

