version: "3.8"

services:
  mongo:
    container_name: mongobd
    build: ./src/server/dbmongo/
    ports:
      - 27017:27017
  mysql: 
    container_name: mysql
    build: ./src/server/dbmysql/
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3306:3306
  ms_menus:
    container_name: menus
    build: ./src/server/ms_1_menus
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 3001:3001
    volumes:
      - ./src/server/ms_1_menus:/usr/app
  ms_orders:
    container_name: orders
    build: ./src/server/ms_2_orders
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 3002:3002
    volumes:
      - ./src/server/ms_2_orders:/usr/app
  ms_cook:
    container_name: cook
    build: ./src/server/ms_3_cook
    depends_on:
      - mysql
      - mongo
    links:
      - mysql
      - mongo
    ports:
      - 3003:3003
    volumes:
      - ./src/server/ms_3_cook:/usr/app
  ms_update_food_storage:
    container_name: food_storage
    build: ./src/server/ms_4_update_food_storage
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 3004:3004
    volumes:
      - ./src/server/ms_4_update_food_storage:/usr/app

